name = "Traveler"
license = "MIT"
licenselink = "https://github.com/rmrobinson/hugo-traveler/blob/master/LICENSE"
description = "A travel-focused blog theme"
homepage = "https://github.com/rmrobinson/hugo-traveler"
tags = []
features = []
min_version = "0.147"

[author]
  name = "Robert Robinson"
  homepage = "https://blog.rmrobinson.ca"
