baseURL = "/"
languageCode = "en-us"
title = "Example Traveler Site"
theme = "hugo-traveler"

[params]
    description = "This is the description of this site"

    [params.author]
        Handle = "exampleHandle"
        FirstName = "Test"
        LastName = "Author"
        Location = "Somewhere, CA"
        AboutPage = "/about"
