baseURL = "http://example.org/"
languageCode = "en-us"
title = "Example Traveler Site"
theme = "hugo-traveler"

[params]
    description = "This is the description of this site"

[author]
   Handle = "exampleHandle"
   FirstName = "Test"
   LastName = "Author"
   Location = "Somewhere, CA"
